try
{
    library "jenkins-shared-lib@${BRANCH_NAME}"
    println("Loaded jenkins-shared-lib from branch: ${BRANCH_NAME}")
}
catch (Exception ex)
{
    println("Problem using BRANCH_NAME, trying main")
    library "jenkins-shared-lib@main"
}

podTemplates.pythonTemplate {
    node(POD_LABEL)
    {
        stage ('Clone Code')
        {
            checkout scm
        }

        stage('Test python3 template')
        {
            container('docker')
            {
                sh 'docker build -f smoketests/template_tests/docker/test_image --tag testimage:latest'
            }
        }
    }
}