try
{
    library "jenkins-shared-lib@${BRANCH_NAME}"
    println("Loaded jenkins-shared-lib from branch: ${BRANCH_NAME}")
}
catch (Exception ex)
{
    println("Problem using BRANCH_NAME, trying main")
    library "jenkins-shared-lib@main"
}

podTemplates.dockerTemplate {
    node(POD_LABEL)
    {
        def env_config = [:]
        stage ('Clone Code')
        {
            checkout scm
            env_config = utils.getConfig()
            env_config.commitHash = utils.getLongCommit()
        }

        stage ('Build Helm Chart')
        {
             [ 'registry' : 'test-registry',  'repository' : 'test-repo' ]

            buildHelmChart (env_config)
        }
    }
}