// https://faun.pub/how-to-get-jenkins-build-job-details-b8c918087030
podTemplate {
    node(POD_LABEL) {

        stage('Clone code') {
            checkout scm
        }

        stage('Clean Testing Area')
        {
            echo "clean old folders"
            def root_items = Hudson.instance.items
            def pipeline_root_items = Hudson.instance.items.getItem("${PIPELINE}")

            items.each { item ->
                if (item.class.canonicalName == 'com.cloudbees.hudson.plugins.folder.Folder')
                {
                    println(item.fullName)
                    //item.delete()
                }
            }

        }
    }
}

