podTemplate {
    node(POD_LABEL) {

        stage('Clone code') {
            checkout scm
        }

        stage('Clean Testing Area')
        {
            echo "clean old folders"

            import hudson.model.*

            jobsToDelete = ["aFolder/aJobInFolder","topLevelJob"]

            deleteChildren()

            def items = Hudson.instance.items

            items.each { item ->
                if (item.class.canonicalName == 'com.cloudbees.hudson.plugins.folder.Folder')
                {
                    println(item.fullName)
                    //item.delete()
                }
            }

        }

        stage('Cleanup')
        {
            cleanWs()
        }
    }
}

