try
{
    library "jenkins-shared-lib@${BRANCH_NAME}"
    println("Loaded jenkins-shared-lib from branch: ${BRANCH_NAME}")
}
catch (Exception ex)
{
    println("Problem using BRANCH_NAME, trying main")
    library "jenkins-shared-lib@main"
}

podTemplates.dockerTemplate {
    node(POD_LABEL)
    {
        stage ('Clone Code')
        {
            checkout scm
        }

        stage ('Build Helm Chart')
        {
            def env_config = utils.getConfig()
            env_config.dockerImage = "test-image"
            buildHelmChart (env_config)
        }
    }
}