apiVersion: v1
kind: Pod
metadata:
  labels:
    ci: openanalytics-r-base
spec:
  containers:
    - name: dind
      image: 196229073436.dkr.ecr.eu-west-1.amazonaws.com/oa-infrastructure/dind
      securityContext:
        privileged: true