jobs:
  - script: >
      pipelineJob("seed_job") {
        displayName('Seed job')

        def repo = 'https://github.com/antman25/jenkins-shared-lib.git'
        
        description("Seed Job")

        definition {
          cpsScm {
            scm {
              git {
                remote { url(repo) }
                branches("main")
                scriptPath('seed_jobs/Jenkinsfile')
                extensions { }  // required as otherwise it may try to tag the repo, which you may not want
              }

            }
          }
        }
      }
      
      
