credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              description: "ARITIFACTORY_CRED"
              id: "ARTIFACTORY_CRED"
              password: not-real-password
              scope: GLOBAL
              username: "jenkins"
          - usernamePassword:
              description: "BITBUCKET_CRED"
              id: "BITBUCKET_CRED"
              password: not-real-password
              scope: GLOBAL
              username: "jenkins"
          - fileSystemServiceAccountCredential:
              id: "kubernetes-svc-account-token-id"
              scope: GLOBAL
jenkins:
  agentProtocols:
    - "JNLP4-connect"
    - "Ping"
  authorizationStrategy:
    projectMatrix:
      permissions:
        - "GROUP:Overall/Read:authenticated"
        - "USER:Overall/Administer:admin"
        - "USER:Overall/Administer:antman"
  clouds:
    - kubernetes:
        containerCap: 10
        containerCapStr: "10"
        credentialsId: "kubernetes-svc-account-token-id"
        jenkinsTunnel: "jenkins-agent.workflow.svc.cluster.local:50000"
        jenkinsUrl: "http://jenkins.workflow.svc.cluster.local:8080"
        name: "k3s-cluster1"
        namespace: "workflow"
        podLabels:
          - key: "jenkins/jenkins-agent-podlbl"
            value: "true"
        serverCertificate: |
          -----BEGIN CERTIFICATE-----
          MIIBdzCCAR2gAwIBAgIBADAKBggqhkjOPQQDAjAjMSEwHwYDVQQDDBhrM3Mtc2Vy
          dmVyLWNhQDE2NzU3NTAxNjcwHhcNMjMwMjA3MDYwOTI3WhcNMzMwMjA0MDYwOTI3
          WjAjMSEwHwYDVQQDDBhrM3Mtc2VydmVyLWNhQDE2NzU3NTAxNjcwWTATBgcqhkjO
          PQIBBggqhkjOPQMBBwNCAASQ1a4PXs/g0AezNNH6HlTdi9An74mfSwY5EnEfLHh3
          ud+k0k5kOAPaQhwcKtDS+yQEf+ot4+5Jbzs0QtXv7aYMo0IwQDAOBgNVHQ8BAf8E
          BAMCAqQwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUT3Hi7SHFkF8Hewp6FB7E
          vvS+4UkwCgYIKoZIzj0EAwIDSAAwRQIgGIQ9t8NXHXAVaJOIWOHr0+ffu+xgySFU
          OOKtvrHl/2kCIQCpKlxjcILLbACC/leH0gNLRWx/HOKYkp0gMvmjnWuTTg==
          -----END CERTIFICATE-----
        serverUrl: "https://kubernetes.default"
        templates:
          - id: "e2b3aa84-5ca9-4336-b8e7-a64203ba3f66"
            name: "default-jnlp"
            namespace: "workflow"
            workspaceVolume:
              dynamicPVC:
                accessModes: "ReadWriteOnce"
                requestsSize: "13Gi"
                storageClassName: "longhorn-retain"
            yamlMergeStrategy: "override"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
  disableRememberMe: false
  globalNodeProperties:
    - envVars:
        env:
          - key: "DELIVERY_BRANCH"
            value: "main"
          - key: "JOB_TESTING_ROOT"
            value: "job-testing"
          - key: "TOOLS_URL"
            value: "https://github.com/antman25/jenkins-shared-lib.git"
          - key: "TOOLS_URL_TESTING"
            value: "http://10.0.0.35/scm/pip/jenkins-shared-lib.git"
  labelAtoms:
    - name: "built-in"
  markupFormatter: "plainText"
  mode: NORMAL
  myViewsTabBar: "standard"
  noUsageStatistics: true
  numExecutors: 0
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 10
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
        - id: "admin"
          name: "Jenkins Admin"
          properties:
            - "favorite"
            - "apiToken"
            - "mailer"
            - "myView"
            - preferredProvider:
                providerId: "default"
            - "timezone"
        - id: "antman"
          name: "antman"
          properties:
            - "favorite"
            - "myView"
            - "timezone"
            - "apiToken"
            - mailer:
                emailAddress: "antman@antlinux.local"
            - preferredProvider:
                providerId: "default"
        - id: "groupa"
          name: "groupa"
          properties:
            - "apiToken"
            - mailer:
                emailAddress: "groupa@antlinux.local"
            - preferredProvider:
                providerId: "default"
            - "favorite"
  slaveAgentPort: 50000
  updateCenter:
    sites:
      - id: "default"
        url: "https://updates.jenkins.io/update-center.json"
  views:
    - all:
        name: "all"
  viewsTabBar: "standard"
globalCredentialsConfiguration:
  configuration:
    providerFilter: "none"
    typeFilter: "none"
unclassified:
  bitbucketEndpointConfiguration:
    endpoints:
      - bitbucketServerEndpoint:
          bitbucketJenkinsRootUrl: "http://10.0.0.50:8080/"
          credentialsId: "BITBUCKET_CRED"
          displayName: "Bitbucket Server"
          manageHooks: true
          serverUrl: "http://10.0.0.35"
  buildDiscarders:
    configuredBuildDiscarders:
      - "jobBuildDiscarder"
  casCGlobalConfig:
    configurationPath: "/tmp/baseline.yaml"
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  hashicorpVault:
    configuration:
      engineVersion: 2
      timeout: 60
  junitTestResultStorage:
    storage: "file"
  location:
    adminAddress: "address not configured yet <nobody@nowhere>"
    url: "http://10.0.0.50:8080/"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  pollSCM:
    pollingThreadCount: 10
tool:
  git:
    installations:
      - home: "git"
        name: "Default"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"
jobs:
  - script: >
      
      pipelineJob("seed-job-gitlab") {
          displayName("!!! Temporary Seed Job - Gitlab URL !!!")
          description("Seed job used to bootstrap")

          environmentVariables {
              env('BRANCH_NAME', 'main')
              env('TOOLS_URL', 'https://github.com/antman25/jenkins-shared-lib.git')
              env('TENANT', 'PIP')
          }
          properties {
            disableConcurrentBuilds {}
          }

          definition {
            cpsScm {
              scm {
                git {
                  remote { url('https://github.com/antman25/jenkins-shared-lib.git') }
                  branches('main')
                  scriptPath('Jenkinsfile')
                  extensions { }  // required as otherwise it may try to tag the repo, which you may not want
                }
              }
            }
          }
      }
      
      pipelineJob("seed-job-bitbucket") {
          displayName("!!! Temporary Seed Job - Bitbucket URL !!!")
          description("Seed job used to bootstrap")

          environmentVariables {
              env('BRANCH_NAME', 'main')
              env('TOOLS_URL', 'http://10.0.0.222:7990/scm/pip/jenkins-shared-lib.git')
              env('TENANT', 'PIP')
          }
          properties {
            disableConcurrentBuilds {}
          }

          definition {
            cpsScm {
              scm {
                git {
                  remote { url('http://10.0.0.222:7990/scm/pip/jenkins-shared-lib.git') }
                  branches('main')
                  scriptPath('Jenkinsfile')
                  extensions { }  // required as otherwise it may try to tag the repo, which you may not want
                }
              }
            }
          }
      }
      
