credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              description: "NEXUS_CREDS"
              id: "NEXUS_CREDS"
              password: this-isnt-my-password
              scope: GLOBAL
              username: "packer"
jenkins:
  agentProtocols:
    - "JNLP4-connect"
    - "Ping"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  clouds:
    - kubernetes:
        containerCap: 10
        containerCapStr: "10"
        jenkinsTunnel: "jenkins-test-agent.default.svc.cluster.local:50000"
        jenkinsUrl: "http://jenkins-test.default.svc.cluster.local:8080"
        name: "kubernetes"
        namespace: "default"
        podLabels:
          - key: "jenkins/jenkins-test-jenkins-agent"
            value: "true"
        serverUrl: "https://kubernetes.default"
        templates:
          - containers:
              - args: "^${computer.jnlpmac} ^${computer.name}"
                envVars:
                  - envVar:
                      key: "JENKINS_URL"
                      value: "http://jenkins-test.default.svc.cluster.local:8080/"
                image: "jenkins/inbound-agent:4.11.2-4"
                name: "jnlp"
                resourceLimitCpu: "512m"
                resourceLimitMemory: "512Mi"
                resourceRequestCpu: "512m"
                resourceRequestMemory: "512Mi"
                workingDir: "/home/jenkins/agent"
            id: "682b16ba5da08f7e7943c84672950ecb58545a090d259587b3f90fe97220a7ba"
            label: "jenkins-test-jenkins-agent"
            name: "default"
            namespace: "default"
            nodeUsageMode: "NORMAL"
            podRetention: "never"
            serviceAccount: "default"
            slaveConnectTimeout: 100
            slaveConnectTimeoutStr: "100"
            yamlMergeStrategy: "override"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
  disableRememberMe: false
  globalNodeProperties:
    - envVars:
        env:
          - key: "TOOLS_URL"
            value: "https://github.com/antman25/jenkins-shared-lib.git"
  labelAtoms:
    - name: "built-in"
    - name: "jenkins-test-jenkins-agent"
  markupFormatter: "plainText"
  mode: NORMAL
  myViewsTabBar: "standard"
  numExecutors: 0
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 1
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 0
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
        - id: "admin"
          name: "Jenkins Admin"
          properties:
            - "apiToken"
            - "mailer"
            - "myView"
            - preferredProvider:
                providerId: "default"
            - "timezone"
  slaveAgentPort: 50000
  updateCenter:
    sites:
      - id: "default"
        url: "https://updates.jenkins.io/update-center.json"
  views:
    - all:
        name: "all"
  viewsTabBar: "standard"
globalCredentialsConfiguration:
  configuration:
    providerFilter: "none"
    typeFilter: "none"
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  envInject:
    enableLoadingFromMaster: false
    enablePermissions: false
    hideInjectedVars: false
  gitHooks:
    allowedOnAgents: false
    allowedOnController: false
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "knownHostsFileVerificationStrategy"
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false
  sSHD:
    port: -1
unclassified:
  buildDiscarders:
    configuredBuildDiscarders:
      - "jobBuildDiscarder"
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  gitSCM:
    addGitTagAction: false
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  globalLibraries:
    libraries:
      - defaultVersion: "main"
        name: "jenkins-shared-lib"
        retriever:
          modernSCM:
            scm:
              git:
                id: "1c85d9ac-3326-4e95-b5a3-737b601e701a"
                remote: "https://github.com/antman25/jenkins-shared-lib.git"
                traits:
                  - "gitBranchDiscovery"
  hashicorpVault:
    configuration:
      engineVersion: 2
      timeout: 60
  junitTestResultStorage:
    storage: "file"
  location:
    adminAddress: "address not configured yet <nobody@nowhere>"
    url: "http://jenkins-test:8080/"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  pollSCM:
    pollingThreadCount: 10
tool:
  git:
    installations:
      - home: "git"
        name: "Default"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"
jobs:
  - script: >
      pipelineJob("seed_job") {
        displayName('Seed job')

        def repo = 'https://github.com/antman25/jenkins-shared-lib.git'
        
        description("Seed Job")

        definition {
          cpsScm {
            scm {
              git {
                remote { url(repo) }
                branches("main")
                scriptPath('seed_jobs/Jenkinsfile')
                extensions { }  // required as otherwise it may try to tag the repo, which you may not want
              }

            }
          }
        }
      }
      
      
