credentials:
  system:
    domainCredentials:
      - credentials:
          - fileSystemServiceAccountCredential:
              id: "k8s-svc-account-token-id"
              scope: SYSTEM
          - usernamePassword:
              description: "ARITIFACTORY_CRED"
              id: "ARTIFACTORY_CRED"
              password: not-real-password
              scope: GLOBAL
              username: "jenkins"
          - usernamePassword:
              description: "BITBUCKET_CRED"
              id: "BITBUCKET_CRED"
              password: not-real-password
              scope: GLOBAL
              username: "jenkins"

jenkins:
  agentProtocols:
    - "JNLP4-connect"
    - "Ping"
  authorizationStrategy:
    projectMatrix:
      permissions:
        - "GROUP:Overall/Read:authenticated"
        - "USER:Overall/Administer:admin"
        - "USER:Overall/Administer:antman"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
  disableRememberMe: false
  globalNodeProperties:
    - envVars:
        env:
          - key: "DELIVERY_BRANCH"
            value: "main"
          - key: "JOB_TESTING_ROOT"
            value: "job-testing"
          - key: "TOOLS_URL"
            value: "https://github.com/antman25/jenkins-shared-lib.git"
          - key: "TOOLS_URL_TESTING"
            value: "http://10.0.0.35/scm/pip/jenkins-shared-lib.git"
  labelAtoms:
    - name: "built-in"
  markupFormatter: "plainText"
  mode: NORMAL
  myViewsTabBar: "standard"
  noUsageStatistics: true
  numExecutors: 0
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 10
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
        - id: "admin"
          name: "Jenkins Admin"
          properties:
            - "apiToken"
            - "mailer"
            - "myView"
            - preferredProvider:
                providerId: "default"
            - "timezone"
        - id: "antman"
          name: "antman"
          properties:
            - "myView"
            - "timezone"
            - "apiToken"
            - mailer:
                emailAddress: "antman@antlinux.local"
            - preferredProvider:
                providerId: "default"
        - id: "groupa"
          name: "groupa"
          properties:
            - "apiToken"
            - mailer:
                emailAddress: "groupa@antlinux.local"
            - preferredProvider:
                providerId: "default"
  slaveAgentPort: 50000
  updateCenter:
    sites:
      - id: "default"
        url: "https://updates.jenkins.io/update-center.json"
  views:
    - all:
        name: "all"
  viewsTabBar: "standard"
globalCredentialsConfiguration:
  configuration:
    providerFilter: "none"
    typeFilter: "none"
unclassified:
  bitbucketEndpointConfiguration:
    endpoints:
      - bitbucketServerEndpoint:
          bitbucketJenkinsRootUrl: "http://10.0.0.50:8080/"
          credentialsId: "BITBUCKET_CRED"
          displayName: "Bitbucket Server"
          manageHooks: true
          serverUrl: "http://10.0.0.35"
          webhookImplementation: NATIVE
  buildDiscarders:
    configuredBuildDiscarders:
      - "jobBuildDiscarder"
  casCGlobalConfig:
    configurationPath: "/tmp/baseline.yaml"
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  hashicorpVault:
    configuration:
      engineVersion: 2
      timeout: 60
  location:
    adminAddress: "address not configured yet <nobody@nowhere>"
    url: "http://10.0.0.50:8080/"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  pollSCM:
    pollingThreadCount: 10
tool:
  git:
    installations:
      - home: "git"
        name: "Default"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"
jobs:
  - script: >
      
      pipelineJob('simple-test')
      {
        definition {
          cpsFlowDefinition {
            
              script("podTemplate { node(POD_LABEL) { stage('test') { sh 'echo test' } } }")
              sandbox(true)
          }
        }
      }
      
      folder('seed-job') {
        properties {
          folderProperties {
            properties {
              stringProperty {
                key('TENANT')
                value("PIP")
              }
            }
          }
        }
      }
      
      pipelineJob("seed-job/gitlab") {
          displayName("!!! Temporary Seed Job - Gitlab URL !!!")
          description("Seed job used to bootstrap")

          environmentVariables {
              env('BRANCH_NAME', 'main')
              env('TOOLS_URL', 'https://github.com/antman25/jenkins-shared-lib.git')
          }
          properties {
            disableConcurrentBuilds {}
          }

          definition {
            cpsScm {
              scm {
                git {
                  remote { url('https://github.com/antman25/jenkins-shared-lib.git') }
                  branches('main')
                  scriptPath('Jenkinsfile')
                  extensions { }  // required as otherwise it may try to tag the repo, which you may not want
                }
              }
            }
          }
      }
      
      pipelineJob("seed-job/bitbucket") {
          displayName("!!! Temporary Seed Job - Bitbucket URL !!!")
          description("Seed job used to bootstrap")

          environmentVariables {
              env('BRANCH_NAME', 'main')
              env('TOOLS_URL', 'http://10.0.0.222:7990/scm/pip/jenkins-shared-lib.git')
          }
          properties {
            disableConcurrentBuilds {}
          }

          definition {
            cpsScm {
              scm {
                git {
                  remote { url('http://10.0.0.222:7990/scm/pip/jenkins-shared-lib.git') }
                  branches('main')
                  scriptPath('Jenkinsfile')
                  extensions { }  // required as otherwise it may try to tag the repo, which you may not want
                }
              }
            }
          }
      }
      
