credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              description: "NEXUS_CREDS"
              id: "NEXUS_CREDS"
              password: this-isnt-my-password
              scope: GLOBAL
              username: "packer"
jenkins:
  agentProtocols:
    - "JNLP4-connect"
    - "Ping"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
  disableRememberMe: false
  globalNodeProperties:
  - envVars:
      env:
      - key: "TOOLS_URL"
        value: "https://github.com/antman25/jenkins-shared-lib.git"
jobs:
  - script: >
      pipelineJob("seed_job") {
        displayName('Seed job')

        def repo = 'https://github.com/antman25/jenkins-shared-lib.git'
        
        description("Seed Job")

        definition {
          cpsScm {
            scm {
              git {
                remote { url(repo) }
                branches("main")
                scriptPath('seed_jobs/Jenkinsfile')
                extensions { }  // required as otherwise it may try to tag the repo, which you may not want
              }

            }
          }
        }
      }
      
      
