credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              description: "NEXUS_CREDS"
              id: "NEXUS_CREDS"
              password: changeme
              scope: GLOBAL
              username: "packer"
jenkins:
  agentProtocols:
    - "JNLP4-connect"
    - "Ping"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
  disableRememberMe: false
  globalNodeProperties:
    - envVars:
        env:
          - key: "TOOLS_URL"
            value: "https://github.com/antman25/jenkins-shared-lib.git"
  labelAtoms:
    - name: "built-in"
  markupFormatter: "plainText"
  mode: NORMAL
  myViewsTabBar: "standard"
  numExecutors: 0
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 1
  scmCheckoutRetryCount: 0
  slaveAgentPort: 50000
  updateCenter:
    sites:
      - id: "default"
        url: "https://updates.jenkins.io/update-center.json"
  views:
    - all:
        name: "all"
  viewsTabBar: "standard"
unclassified:
  buildDiscarders:
    configuredBuildDiscarders:
      - "jobBuildDiscarder"
  casCGlobalConfig:
    configurationPath: "/tmp/baseline.yaml"
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  globalLibraries:
    libraries:
      - defaultVersion: "main"
        name: "jenkins-shared-lib"
        retriever:
          modernSCM:
            scm:
              git:
                id: "1c85d9ac-3326-4e95-b5a3-737b601e701a"
                remote: "https://github.com/antman25/jenkins-shared-lib.git"
                traits:
                  - "gitBranchDiscovery"
  hashicorpVault:
    configuration:
      engineVersion: 2
      timeout: 60
  location:
    adminAddress: "address not configured yet <nobody@nowhere>"
    url: "http://jenkins-test:8080/"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  pollSCM:
    pollingThreadCount: 10
tool:
  git:
    installations:
      - home: "git"
        name: "Default"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"
jobs:
  - script: >
      pipelineJob("seed_job") {
        displayName('Seed job')

        def repo = 'https://github.com/antman25/jenkins-shared-lib.git'
      
        description("Seed Job")

        definition {
          cpsScm {
            scm {
              git {
                remote { url(repo) }
                branches("main")
                scriptPath('seed_jobs/Jenkinsfile')
                extensions { }  // required as otherwise it may try to tag the repo, which you may not want
              }

            }
          }
        }
      }
      
      
